# Generated by Django 5.2 on 2025-04-27 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aktor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=255)),
                ('nazwisko', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gatunek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SalaTeatralna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
                ('liczba_rzedow', models.PositiveIntegerField()),
                ('miejsca_w_rzedzie', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rezerwacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_utworzenia', models.DateTimeField(auto_now_add=True)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezerwacje', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sztuka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=255)),
                ('opis', models.TextField()),
                ('aktorzy', models.ManyToManyField(blank=True, related_name='sztuki', to='teatr_service.aktor')),
                ('gatunki', models.ManyToManyField(blank=True, related_name='sztuki', to='teatr_service.gatunek')),
            ],
        ),
        migrations.CreateModel(
            name='Przedstawienie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czas_wystepu', models.DateTimeField()),
                ('sala_teatralna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='przedstawienia', to='teatr_service.salateatralna')),
                ('sztuka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='przedstawienia', to='teatr_service.sztuka')),
            ],
        ),
        migrations.CreateModel(
            name='Bilet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rzad', models.PositiveIntegerField()),
                ('miejsce', models.PositiveIntegerField()),
                ('przedstawienie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilety', to='teatr_service.przedstawienie')),
                ('rezerwacja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilety', to='teatr_service.rezerwacja')),
            ],
            options={
                'unique_together': {('przedstawienie', 'rzad', 'miejsce')},
            },
        ),
    ]
